# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kibe < Formula
  desc ""
  homepage "https://github.com/momarques/kibe"
  version "0.0.4"

  on_macos do
    url "https://github.com/momarques/kibe/releases/download/v0.0.4/kibe_0.0.4_darwin_all.tar.gz"
    sha256 "7bd424755a7a67bd1c52f84a55515c3597926de71c62435e6232e763e94e29f8"

    def install
      bin.install "kibe"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/momarques/kibe/releases/download/v0.0.4/kibe_0.0.4_linux_arm64.tar.gz"
      sha256 "562c0b5cbadf17a6f401910daa99b3c9704d745127f51037c4d01d16b80d4489"

      def install
        bin.install "kibe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/momarques/kibe/releases/download/v0.0.4/kibe_0.0.4_linux_amd64.tar.gz"
      sha256 "73ce27ffe75edb2c2eb3d7c7fb116c340ea89c55f9a9cc2759279aeee2f658b5"

      def install
        bin.install "kibe"
      end
    end
  end
end
